### ISSUE TITLE
[Bug Report] Аny links in the chat are not opened in the defailt browser

### ISSUE THREAD

**Issue by briney83** [cstayyab/WALC#59] opened 2020-07-20 05:52 UTC
**Describe the bug**
Аny links in the chat are not opened in the default browser

**WALC Installation Type:** AppImage

**To Reproduce**
1. Open WALC
2. Click on any link in any chat
3. nothing...

**Expected behavior**
link is opened in default browser

**Did you try closing and then opening it back?:** Yes 

**System Information (please complete the following information):**
 - OS/Distro: Manjaro GNOME 20.0.3/Ubuntu 20.04

**Additional context**
snap version is okok

**Comment by Zzombiee2361** [comment] 2020-07-20 07:25
Duplicate of #42. My only suggestion is to try changing your default browser, restart WALC, then see if it fixes the issue. I don't really know what caused this and I really can't reproduce this. Probably a bug with electron-builder packaging.

**Comment by briney83** [comment] 2020-07-20 13:22
> Duplicate of #42. My only suggestion is to try changing your default browser, restart WALC, then see if it fixes the issue. I don't really know what caused this and I really can't reproduce this. Probably a bug with electron-builder packaging.

Yes, the same. After unpacking it works without the AppRun script in Google Chrome browser.

**Comment by briney83** [comment] 2020-08-09 05:26
WALC.desktop[19494]: /opt/google/chrome/google-chrome: error while loading shared libraries: /tmp/.mount_WALC.A3Skqpa/usr/lib/libXtst.so.6: file too short

-rw-r--r-- 1 briney briney 0 авг  9 12:25 libappindicator.so.1
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libgconf-2.so.4
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libindicator.so.7
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libnotify.so.4
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libXss.so.1
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libXtst.so.6

**Comment by bkmo** [comment] 2020-08-16 18:28
New release didn't fix the links opening up in chromium.

**Comment by Zzombiee2361** [comment] 2020-08-17 01:40
_sigh_ I told @cstayyab to make sure that the libraries are not empty. [Here, try my own built AppImage.](https://drive.google.com/file/d/1D6BUOPeW3fLLJibM7o5RI4wf3vfMkZFo/view?usp=sharing) I don't know exactly what's wrong with the build process, probably he doesn't have the dependency installed on his machine.

**Comment by bkmo** [comment] 2020-08-17 04:11
Your image works just fine....thank you

**Comment by briney83** [comment] 2020-08-17 11:07
> [Here, try my own built AppImage](https://drive.google.com/file/d/1D6BUOPeW3fLLJibM7o5RI4wf3vfMkZFo/view?usp=sharing)

thanks!!!

**Comment by Zzombiee2361** [comment] 2020-10-27 16:31
Should be fixed with the latest release

**Closed by Zzombiee2361** 2020-10-27 16:31 UTC
Labels: bug
