### ISSUE TITLE
[Bug Report] Does not determine Chrome version

### ISSUE THREAD

**Issue by MoonDragon-MD** [cstayyab/WALC#24] opened 2020-04-26 20:08 UTC
Hi, from today walc gives the error to update chrome to version 49+, even if I installed version 81.0.4044.122.
Can you please fix it?
Thanks

**Comment by Zzombiee2361** [comment] 2020-04-27 06:03
Hi, this is an electron app and your chrome version doesn't matter. Your issue is most likely a duplicate of #21, please try the workaround provided by @cstayyab and see if it fixes the issue.

**Comment by MoonDragon-MD** [comment] 2020-04-27 15:11
Thanks for getting back to me.
I cleaned as described and it works, but as soon as I close and reopen Walc I have the same problem again.
Can you think of another solution?
Thank you

**Comment by Zzombiee2361** [comment] 2020-04-27 17:15
Did you try deleting configuration at `~/.config/WALC` then scanning for QR code again?

**Comment by cstayyab** [comment] 2020-04-27 21:33
@MoonDragon-MD you didn't specify any details required by Bug Report. Can you please tell which method you used to setup WALC? Are you using AppImage or Snap? Also which Linux distro are you using and it's version? All this information might be helpful in detecting the root cause of the issue.

**Comment by MoonDragon-MD** [comment] 2020-04-28 15:14
Hello, I'm using ubuntu 18.04.4 x64 (x11 server) with 
1) Gnome 3.28.2
2) Python 2.7.17 + Python 3.6.9 + pip 20.0.2 (python 3.6)
3) Snap 2.44.3 
4) nvidia-driver-440 + cuda 9.1.85-3
I installed Walc with "Ubuntu software center" (gnome software), I put permissions to access the home folder, in fact I created the folder ~/snap/walc where to save whatsapp attachments.
The version of Walc is 0.1.6
I can't find the ~/.config/WALC folder must be somewhere else, I can't even find it with "locate WALC".
If you need any more information tell me

**Comment by cstayyab** [comment] 2020-05-04 09:29
@MoonDragon-MD  if you can't find "~/.config/WALC" and the workaround specified in #21 did not work for you please try deleting "~/snap/walc" and reopen walc. I hope this will help reset WALC

**Comment by MoonDragon-MD** [comment] 2020-05-04 15:09
Thank you, it looks like the problem is solved now.

**Closed** 2020-05-04 16:24 UTC
