### ISSUE TITLE
Tray icon not showing after OS suspends

### ISSUE THREAD

**Issue by TheLumbee** [cstayyab/WALC#91] opened 2020-12-20 07:33 UTC
Tray icon disappears after OS suspends.

WALC Installation Type: Snap

**To Reproduce**
1. Open WALC
2. Suspend computer (in my case closing laptop screen)
3. WALC process still running correctly otherwise, but no tray icon. 

**Expected behavior**
Expect tray icon to still show in tray. Not showing at all

**Did you try closing and then opening it back?:** Yes. Works fine after restarting application.

 - OS/Distro: Ubuntu 20.04
 - Gnome 3.36.4

**Comment by cstayyab** [comment] 2020-12-21 07:47
Closing as duplicate of #40

**Closed by cstayyab** 2020-12-21 07:47 UTC
Labels: bug
