### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by jneusse** [cstayyab/WALC#82] opened 2020-11-24 23:48 UTC
**Describe the bug**

I cant use my microphone... seems its not detected by the app

**WALC Installation Type:** AppImage / Snap

**To Reproduce**

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro:

**Additional context**

**Comment by cstayyab** [comment] 2020-12-09 05:43
Closing as Duplicate of #63

**Closed by cstayyab** 2020-12-09 05:43 UTC
Labels: bug
