### ISSUE TITLE
[Bug Report] Clicked link in chat does not open in browser

### ISSUE THREAD

**Issue by bkmo** [cstayyab/WALC#42] opened 2020-06-03 20:22 UTC
0.1.9 appimage installed on Manjaro KDE 20.0.1

Clicking an HTTP link in a chat causes Brave Browser to be launched, but never opens.
In KDE I see the bouncing icon launch feedback of Brave browser but the browser never opens.

I would expect for it to open a new tab if Brave is running, or launch a new instance of brave.
This happened also when running under Kubuntu 20.04

**Comment by cstayyab** [comment] 2020-06-03 22:36
Please change you default browser and see if the issue persists. This is to check if the problem is specifically related to a particular browser.

**Comment by bkmo** [comment] 2020-06-03 22:53
Changed to Firefox and it opens correctly.

**Comment by cstayyab** [comment] 2020-06-04 20:27
> Changed to Firefox and it opens correctly.

Hence issue is not specifically related to WALC. Either it is an issue with Electron or Brave Browser is not handling OS URL API Correctly. 

So I am closing this.

**Closed by cstayyab** 2020-06-04 20:27 UTC
Labels: bug

**Comment by bkmo** [comment] 2020-06-05 01:15
Whatever the issue, it only works with Firefox. Chromium browsers like Google Chrome and Brave will not open.

**Comment by bkmo** [comment] 2020-07-11 20:34
This issue is still present in the latest version. I cannot run it like this. On chromium browsers the link does not open the browser or a new window.

**Comment by Zzombiee2361** [comment] 2020-07-12 02:32
Does it also happens with other electron app? We can't really fix this, it's probably a problem with your distro or a problem with electron which we could only try to update it, but we can't guarantee if it's going to fix this.

**Comment by bkmo** [comment] 2020-07-12 05:02
Nope, only with this app. I have my own apps using electron and they work ok. I build using electron 9.0.2 or 8.3.1 because of the tray icon behavior.

**Comment by Zzombiee2361** [comment] 2020-07-12 05:10
Can you try building WALC yourself? I really can't reproduce this no matter what. Maybe try doing it on a new linux account, could be a problem with your config.

**Comment by bkmo** [comment] 2020-07-12 05:14
Tomorrow I'll boot another OS and give it a try. All I know is the last time I switched to Firefox as my default browser it opened in Firefox. But with Chrome, Chromium, or Brave as default it does nothing. I see them try to load then fail.

**Comment by bkmo** [comment] 2020-07-15 01:41
I created a new user, downloaded  WALC appimage, and logged into whatsapp. Clicking on a link opened up firefox which was closed. I then went to settings and selected chromium as the default browser. Clicking on the same link brought up the loading animation with the chromium icon, but it never opened. Same issue as I always had with all chromium based browsers. Using my own app built with Electron it opens fine with chromium browsers.

**Comment by Zzombiee2361** [comment] 2020-07-15 05:51
Glad that worked for you. Must be some weird configuration with package lock or node modules, and starting new apparently works. For the dark mode toggle, can you try open the debug tool and see if there's any error on the console?

**Comment by bkmo** [comment] 2020-07-16 07:09
One thing I discovered was that if I extract the appimage and run it from the walc executeable it opens links in chromium just fine. If I run it from the AppRun script it is broken.

**Comment by Zzombiee2361** [comment] 2020-07-16 07:23
That's an interesting finding. So it has problem with AppImage. Maybe try building your own electron app as AppImage and confirm this. I don't know what to do next though, maybe report it to `electron-builder` repo?

**Comment by bkmo** [comment] 2020-07-16 07:28
Seems to me it is something that is the AppRun script. One of the path exports or something. I have other electron programs as appimages that  don't have this issue.

**Comment by briney83** [comment] 2020-07-20 13:20
> I run it from the AppRun script it is broken. Everything is working fine without executing from AppRun

Yes, the same. After unpacking it works without the AppRun script

**Comment by Zzombiee2361** [comment] 2020-07-20 13:38
Why is this seems to happen only on manjaro?

**Comment by briney83** [comment] 2020-08-08 08:22
авг 08 15:20:25 ACER-E5 WALC.desktop[19494]: /opt/google/chrome/google-chrome: error while loading shared libraries: /tmp/.mount_WALC.A3Skqpa/usr/lib/libXtst.so.6: file too short

**Comment by briney83** [comment] 2020-08-09 06:09
I unpacked the .appimage, replaced the usr/lib/libXtst.so.6 library, built a new .appimage using linuxdeployqt-7-x86_64. And now links are then opened in the default browser. Check why there are zero length libraries in usr/lib

-rw-r--r-- 1 briney briney 0 авг  9 12:25 libappindicator.so.1
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libgconf-2.so.4
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libindicator.so.7
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libnotify.so.4
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libXss.so.1
-rw-r--r-- 1 briney briney 0 авг  9 12:25 libXtst.so.6

**Comment by Zzombiee2361** [comment] 2020-08-09 08:43
Good finding! May I ask how did you find the error?

Regarding your finding, apparently this is a problem when building WALC on @cstayyab side. The reason I'm unable to reproduce it is because I'm building the AppImage myself and those files has the correct size on my AppImage.

**Comment by briney83** [comment] 2020-08-09 09:38
> Хорошая находка! Могу я спросить, как вы обнаружили ошибку?
I opened journalctl -f in terminal and clicked on the link in WALC

**Comment by briney83** [comment] 2020-08-09 09:39
> Хорошая находка! Могу я спросить, как вы обнаружили ошибку?

I opened journalctl -f in terminal and clicked on the link in WALC

**Comment by briney83** [comment] 2020-08-09 09:41
> Good finding! May I ask how did you find the error?

I opened journalctl -f in terminal and clicked on the link in WALC

**Comment by bkmo** [comment] 2020-08-11 20:08
Will this get fixed?

**Comment by Zzombiee2361** [comment] 2020-08-11 23:42
Sure, I just have to compile and release it. But there's a few bug that I found that has to be fixed first.

**Comment by bkmo** [comment] 2020-08-12 00:15
Just curious, thanks for the reply, keep up the good work....
