### ISSUE TITLE
[Bug Report] Automatically closes when internet connection breaks and doesn't reopen again

### ISSUE THREAD

**Issue by mishuvs** [cstayyab/WALC#56] opened 2020-07-13 06:47 UTC
**Describe the bug**
After internet connection breaks, it automatically quits. Then when I try to reopen it automatically displays the exit promptly and doesn't open the app. Whether I click 'yes' or 'no' for exit prompt, it exits either way.

**WALC Installation Type:** AppImage / Snap

**To Reproduce**
1. Break internet connection
2. WALC will exit
3. search and click on WALC icon again to open it up
4. WALC shows exit prompt
5. Click either 'yes' or 'no', WALC exits

**Expected behavior**
It should not close on internet disconnection, and there shouldn't be any problems in reopening.

**Did you try closing and then opening it back?:** Yes

**Screenshots**

![Screenshot from 2020-07-13 12-15-10](https://user-images.githubusercontent.com/35009811/87278631-9219eb00-c502-11ea-9fec-b29828b855ee.png)

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 18.04

**Comment by Zzombiee2361** [comment] 2020-07-19 03:49
What version of WALC are you on? Make sure you're on the latest WALC (0.1.10 currently). And did you install WALC from snap?

**Comment by mishuvs** [comment] 2020-07-19 13:12
Yes, I am using 0.1.10. Yes, I installed using snap.

**Comment by bjeanes** [comment] 2020-07-26 00:42
Same. 0.1.10, instlled with snap

**Comment by Zzombiee2361** [comment] 2020-07-26 01:42
How did you start WALC? Did you start it manually or automatically on startup? I absolutely have no idea about WALC closing when internet breaks, but I can make it so WALC will show instead of showing that weird exit prompt.

**Comment by bjeanes** [comment] 2020-07-26 01:58
I am opening by hitting the icon in Gnome dock

**Comment by bjeanes** [comment] 2020-07-26 02:28
I don't know about the correlation between internet connection break and this happening, but it has happened after sleeping so it sounds plausible.

**Comment by Zzombiee2361** [comment] 2020-07-26 02:30
Ah, why didn't you say so? It's a duplicate of #40 then

**Comment by bjeanes** [comment] 2020-07-26 02:31
@Zzombiee2361 yes, I think you're right. #40 looks pretty accurate

**Closed** 2020-08-09 09:00 UTC
Labels: bug
