### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Aizaz-hash** [cstayyab/WALC#132] opened 2021-04-23 16:13 UTC
**Describe the bug**
I was trying to send a voice message into a group, but it was throwing me an error or no microphone found, I attend the Microsoft Teams meeting with the same microphone, but WhatsApp is continuously throwing a microphone not found error.

**Expected behavior**
it should have recorded my voice message and send it to the group when the microphone is already attached to the laptop.

**Did you try closing and then opening it back?:** Yes / No
Yes

**Screenshots**
If applicable, add screenshots ![bug](https://user-images.githubusercontent.com/73718177/115899419-2a70d300-a478-11eb-8612-5b7b8e3c842f.jpg)

**Comment by cstayyab** [comment] 2021-04-23 20:54
duplicate of #129

**Closed by cstayyab** 2021-04-23 20:54 UTC
Labels: bug
