### ISSUE TITLE
[Bug Report] WALC-Exit-confirmation-window not readable 

### ISSUE THREAD

**Issue by Redevectored** [cstayyab/WALC#66] opened 2020-09-11 10:40 UTC
Hello there, 

**Describe the bug**
When closing the WALC-window, the pop-up box asking for confirmation to exit doesn't show normal letters, but instead whitespaces?

**WALC Installation Type:** AppImage / Snap
Snap

**To Reproduce**
1. Go to WALC
2. Click on "Close Window" (red x) from any point in the app. At Login or when logged in. 
3. See error

**Expected behavior**
Confirmation to exit window written with normal letters. 

**Did you try closing and then opening it back?:** Yes / No
Yes. 

![image](https://user-images.githubusercontent.com/57843146/92912990-a27b1300-f42a-11ea-9e86-4f30e4637d3f.png)

OS/Distro: Fedora Workstation 32
Desktop-Environment: XFCE v.4.14

Thank you very much for your hard work.

**Comment by Zzombiee2361** [comment] 2020-09-11 13:17
Duplicate of #35. Go check the workaround I posted there.

**Comment by Redevectored** [comment] 2020-09-11 16:12
Thank you, and apologies for the duplication.

**Closed** 2020-09-11 16:13 UTC
Labels: bug

**Comment by Zzombiee2361** [comment] 2020-09-11 16:21
And? Is your issue actually solved?
