### ISSUE TITLE
[Bug Report] Sent Message state isn't being updated

### ISSUE THREAD

**Issue by Jey027** [cstayyab/WALC#71] opened 2020-10-17 12:23 UTC
**Describe the bug**

**WALC Installation Type:** Installed from Ubuntu App-store

**To Reproduce**
1. Literally just send a message

**Expected behavior**
when I send the message, it shows the clock, even tho the person did read the message and is able to respond just fine

**Did you try closing and then opening it back?:** Yes 

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Additional context**
After a couple minutes it shows the 'real' state, like for example if they read it or not, but it takes quiet a bit sometimes for that to show up.
![Bildschirmfoto von 2020-10-17 14-21-57](https://user-images.githubusercontent.com/68896046/96337041-235da800-1084-11eb-8c92-a049acbe3c6b.png)

**Comment by Zzombiee2361** [comment] 2020-10-27 16:16
Duplicate of #70

**Closed by Zzombiee2361** 2020-10-27 16:16 UTC
Labels: bug
