### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Ritvik-Sapra** [cstayyab/WALC#127] opened 2021-03-24 18:25 UTC
Since the official WhatsApp web desktop app for Windows has a video call and an audio call option, it would be amazing if that could be incorporated in WALC client too.

**Comment by danger-ahead** [comment] 2021-03-26 18:01
yes that would be amazing

**Comment by cstayyab** [comment] 2021-05-03 00:21
Duplicate of #126

**Closed by cstayyab** 2021-05-03 00:21 UTC
