### ISSUE TITLE
[ Feature Request ]  Dark theme option

### ISSUE THREAD

**Issue by bkmo** [cstayyab/WALC#30] opened 2020-05-15 19:29 UTC
Most everything I have is dark themed. It would be nice if this could be dark themed as well.

**Comment by Zzombiee2361** [comment] 2020-05-15 20:46
Duplicate of #22. Although I'd like to see this implemented anyway using some custom css.

**Comment by bkmo** [comment] 2020-05-15 20:49
Thank you and yes I have seen another app doing a dark theme with some sort of  custom css.

**Comment by cstayyab** [comment] 2020-05-15 21:57
Although it was decided that WALC will wait for WhatsApp to release Dark Mode for WhatsApp but due to overwhelming requests, I plan to implement. Vote for this Feature if you also want to see it happen. Here is the FeatHub Link for this feature.  
Please Vote it here to record its demand: https://feathub.com/cstayyab/WALC/+9

**Comment by cstayyab** [comment] 2020-05-16 06:58
Implemented this feature using WhatsApp Web Native Dark Mode which is currently in Beta and isn't released yet.

**Closed** 2020-05-16 06:59 UTC
Labels: duplicate, enhancement

**Comment by Gustav0ar** [comment] 2020-05-20 13:42
@cstayyab Whatsapp Web already has that feature hidden. You can activate it by adding the class **dark** to the body tag. I tested with WALC and works fine. Maybe you could create a setting for adding that in a user friendly way.

Just change:
```
<body class="web">
...
</body>
```

to:

```
<body class="web dark">
...
</body>
```
