### ISSUE TITLE
Background running

### ISSUE THREAD

**Issue by GnosGnas** [cstayyab/WALC#74] opened 2020-10-31 17:59 UTC
**Describe the bug**

When I start the app fresh the app runs in the background and there is a symbol also at the top right. When I leave it open for too long or when the system goes into sleep, it stops running in the background and I don't see any notification.

**WALC Installation Type:** AppImage / Snap

**To Reproduce**

**Expected behavior**

It must run in the background without loosing the connection. This doesn't happen with What's Desk.

**Did you try closing and then opening it back?:** Yes / No

Yes, It works whenever I start it fresh

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Additional context**

**Comment by Zzombiee2361** [comment] 2020-10-31 23:06
Did you try looking at process manager to see if WALC exists or not? This could be a bug where the tray is missing after unlocking, see #40. If WALC process actually exists, then it's a duplicate of that issue

**Comment by GnosGnas** [comment] 2020-11-02 05:13
Can you explain further what you mean by duplicate of that issue? I checked the process manager and WALC is running in the background but I am not getting any notifications or the icon on the top right.

**Comment by Zzombiee2361** [comment] 2020-11-02 05:38
The issue I linked says that the tray icon is missing after unlocking. I'm not quite sure about the notification though. What happens when you reopen WALC again while that happen? Does whatsapp reloads again or is it opens where you left off?

**Comment by GnosGnas** [comment] 2020-11-02 17:59
When I open again, it opens where I left it off. After this for a brief amount of time it gives notifications, and then I guess it disconnects. That part is not much of a problem, but that icon would indicate if there are new messages (at least when it is connected). I get that icon only when I reinstall the application, and I did the reinstallation twice to check if that's the case. Also, it does not connect automatically when I close it. Like if I open my phone for some reason it, I would expect both the phone and laptop to give the WhatsApp notifications, but that happens only when WALC is kept open or is very recently closed. 
Also, it would be great if the icon shows if it's connected or not.

**Comment by Zzombiee2361** [comment] 2020-11-02 18:21
So this is pretty much confirm that this issue is a duplicate or at least similar to #40. If you see the linked issue, there's not much that we can do. We probably could update electron hoping that the issue is fixed. My suggestion if you're using snap is try to use the AppImage version. I personally use it, and apparently has much less issue than snap.

> Also, it would be great if the icon shows if it's connected or not.

This already exists, if the network is disconnected the tray icon turns gray and even a notification is sent

**Comment by GnosGnas** [comment] 2020-11-03 07:14
How do I install the AppImage version? I am not very familiar with Linux.

Also, this app has been great for me compared to many other servers so cheers to the team!

**Comment by Zzombiee2361** [comment] 2020-11-03 09:39
Just download AppImage file from [here](https://github.com/cstayyab/WALC/releases/download/v0.1.11-Post/walc.AppImage) then run the file

**Comment by GnosGnas** [comment] 2020-11-03 18:50
Its showing me permission denied.

**Comment by Zzombiee2361** [comment] 2020-11-04 01:35
When I say "run the file", I mean mark it as executable then open it. Usually you can go to properties > permission > checkbox that says executable in it. Just Google it if you're still confused

**Closed** 2020-11-05 07:28 UTC
Labels: bug
