### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by phaltness** [cstayyab/WALC#128] opened 2021-04-05 11:16 UTC
Hi there,
when Video calls will be available? how we could help You to release the Feature?
BR. Pavel

**Comment by cstayyab** [comment] 2021-04-05 21:15
Hey @phaltness , We are not yet trying to implement any feature ahead of WhatsApp Web because we totally rely on them for any feature. So unless WhatsApp Provides any such option we won't be releasing one.

**Comment by cstayyab** [comment] 2021-04-23 20:53
Duplicate of #127

**Closed by cstayyab** 2021-04-23 20:53 UTC
