### ISSUE TITLE
[Bug Report] Snap does not start on Ubuntu 20.04

### ISSUE THREAD

**Issue by janosbrodbeck** [cstayyab/WALC#55] opened 2020-07-12 18:02 UTC
**Describe the bug**
WALC snap simply does not start on Ubuntu 20.04. There is no error message or anything, it's just not popping up. I've even tried to start it with `snap run walc` from the terminal - no feedback. With `sudo snap run walc` I'm getting `mkdir: cannot create directory '/run/user/0': Permission denied`.

**WALC Installation Type:** Snap

**To Reproduce**
Ubuntu 20.04
Install from snapcraft: `sudo snap install walc`
Try to start?

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04, up to date

**Additional context**
I don't know whether there are more ways to get more debug informations...
AppImage works flawlessly.

**Comment by ronny332** [comment] 2020-08-01 09:05
Can't reproduce it, works since my migration so 20.04 LTS without issues.

**Comment by dobroweb** [comment] 2020-09-07 04:59
I confirm there is a problem in Ubuntu 20.04. But it does not appear immediately, but after a while. It is manifested first by the disappearance of the icon from the tray, and then the program window stops opening altogether. Helps only reinstallation WALC. Sorry for my English.

**Comment by lulis** [comment] 2020-10-01 12:25
Same problem here on Ubuntu 20.04 fresh install: `walc` snap not launching, no warnings at all.
Removing and re-installing didn't solve it.

[Debugging](https://snapcraft.io/docs/debug-snaps) I've found some policy violation errors for the folowing user directories: `Downloads`, `Images` and `Templates`, like this:
```
hostname audit[9961]: AVC apparmor="DENIED" operation="open" profile="snap.walc.walc" name="/mnt/docs/Downloads/" pid=9961 comm="head" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```
On my user case, these directories are actually symlinks. 
I've renamed the symlinks temporarily to something else (like `Downloads2`), then launched  `walc` successfully with some messages at command prompt:
```
/home/user/Downloads was removed, reassigning DOWNLOAD to homedir
```
After this I can run `walc` successfully, even when I renamed the symlinks back to original ;)

Hope it helps someone.

**Comment by janosbrodbeck** [comment] 2020-10-01 16:27
@lulis Fix does not apply to my problem, sadly.
Funny thing: I've found out, that when I install `walc` in devmode (snap install walc --devmode) it works ¯\_(ツ)_/¯

**Comment by cstayyab** [comment] 2020-12-09 06:12
Closing this issue as non-reproducible. If your are still facing a problem, please start a discussion in [Troubleshooting](https://github.com/cstayyab/WALC/discussions?discussions_q=category%3ATroubleshooting) category of WALC Discussion Board.

**Closed by cstayyab** 2020-12-09 06:12 UTC
Labels: bug
