### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by alexandresobral2004** [cstayyab/WALC#77] opened 2020-11-06 22:06 UTC
**Describe the bug**
THE MICROPHONE NOT WORKING

**WALC Installation Type:** AppImage / Snap

**To Reproduce**

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro:

**Additional context**

**Comment by cstayyab** [comment] 2020-11-07 04:32
Duplicate of #63

**Closed by cstayyab** 2020-11-07 04:32 UTC
Labels: bug
